spring:
  application:
    name: crmedu
  liquibase:
    enabled: true
    default-schema: crmedu
    liquibase-schema: crmedu
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect