name: Generate and publish docs

on:
  push:
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME}}
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 5435:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Move Javadoc to gh-pages folder
        run: mkdir -p gh-pages/javadoc && mv build/docs/javadoc/* gh-pages/javadoc/

      - name: Start application for OpenAPI generation
        run: ./gradlew bootRun & sleep 10

      - name: Generate OpenAPI spec
        run: ./gradlew generateOpenApiSpec

      - name: Fetch OpenAPI spec
        run: curl -o build/generated/openapi.json http://localhost:8080/v3/api-docs

      - name: Fix OpenAPI version for Swagger UI
        run: |
          cat build/generated/openapi.json | jq '{openapi: "3.0.1", info: .info, servers: .servers, paths: .paths, components: .components}' > temp.json
          mv temp.json build/generated/openapi.json

      - name: Convert OpenAPI spec
        uses: Legion2/swagger-ui-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output: gh-pages/swagger
          spec-file: build/generated/openapi.json

      - name: Upload Docs Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: gh-pages

  publish-docs:
    needs: generate-docs
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Docs Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: gh-pages

      - name: Create index.html for GitHub Pages
        run: echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=swagger/index.html"></head><body></body></html>' > gh-pages/index.html

      - name: Publish Javadoc & Swagger to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false